from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('menuproductos/', views.menuproductos, name='menuproductos'),
    path('menuproductos/barnices/', views.barnices, name='barnices'),
    path('menuproductos/cabello/', views.cabello, name='cabello'),
    path('menuproductos/cuidado/', views.cuidado, name='cuidado'),
    path('menuproductos/perfumes/', views.perfumes, name='perfumes'),
    path('menuproductos/lociones/', views.lociones, name='lociones'),
    path('menuproductos/maquillaje/', views.maquillaje, name='maquillaje'),
    path('opiniones/', views.opiniones, name='opiniones'),
    path('servicios/', views.servicios, name='servicios'),
    path('manicura/', views.manicura, name='manicura'),
    path('tratamiento/', views.tratamiento, name='tratamiento'),
    path('depilaciones/', views.depilaciones, name='depilaciones'),
    path('manicura_conv/', views.manicura_conv, name='manicura_conv'),
    path('extensiones/', views.extensiones, name='extensiones'),
    path('tintes/', views.tintes, name='tintes'),
    path('pedicure/', views.pedicure, name='pedicure'),
    path('cortes/', views.cortes, name='cortes'),
    path('contacto/', views.contacto, name='contacto'),
    path('vercitas/', views.vercitas, name='vercitas'),
    path('unete/', views.unete, name='unete'),
    path('login/', views.login, name='login'),
    path('recuperar/', views.recuperar, name='recuperar'),
    path('citas/', views.citas, name='citas'),
    path('login/cerrar', views.cerrar, name='cerrar'),
    path('registro/', views.registro, name='registro'),
    path('citas/', views.citas, name='citas'),
    path('tips/', views.tips, name='tips'),
]
